version: "3.7"
volumes:
  grafana-data:
  prometheus-data:
services:
  redis-master-0:
    image: redis:6.0.9
    ports:
      - "7000:6379"
    volumes: 
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    network_mode: host
 
###grafana  
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    network_mode: host
    volumes:
        - grafana-data:/var/lib/grafana
  ##redis
  redis_exporter:
    image: oliver006/redis_exporter:v1.13.1-alpine
    ports:
      - 9121:9121
    network_mode: host
  
  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    network_mode: host
  
